# @package _global_

defaults:
  - ppo
  - override /algo: ppo_recurrent
  - override /model_manager: ppo_recurrent
  - _self_

algo:
  per_rank_num_batches: 8
  per_rank_sequence_length: 16
  total_steps: 50000000000000
  rollout_steps: 512
  update_epochs: 8
  cnn_keys:
    encoder: [rgb]
  mlp_keys:
    encoder: ['ev','thermo','collision','touch']

# Environment
env:
  num_envs: 1
  frame_stack: 4
  screen_size: 64

buffer:
  memmap: False
